#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	Set Volume : 0~100
	*/
	setSoundVolume(10);


	playTone(2000, 10);
	while(bSoundActive);

	/*
	Immediately play tone at frequency & duration ahead of queued requests.
	*/
	playImmediateTone(2000, 20);
	while(bSoundActive);

	/*
	See the definition of TSounds
	*/
	playSound(soundUpwardTones);
	while(bSoundActive);


	setSoundVolume(50);
	/*
	You can locate built-in soundfile through this menu.
		Robot->LEGO Brick->File Management Utility
		DIR : /home/root/lms2012/resources/Sounds
	*/
	while(!bSoundQueueAvailable);
	playSoundFile("Dog bark 1");
	while(bSoundActive);

	while(!bSoundQueueAvailable);
	playSoundFile("Laughing 1");
	while(bSoundActive);

	while(!bSoundQueueAvailable);
	playSoundFile("Dog sniff");
	while(bSoundActive);

	while(!bSoundQueueAvailable);
	playSoundFile("Crying");
	while(bSoundActive);

}
