#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Built in speaker cannot play from (E and 8 Octave).
*/
const int MUSIC_NOTE[12][9] = {
	16,33,65,131,262,523,1047,2093,4186,
	17,35,69,139,278,554,1109,2218,4435,
	18,37,73,147,294,587,1175,2349,4699,
	20,39,78,156,311,622,1245,2489,4978,
	21,41,82,165,330,659,1319,2637,5274,
	22,44,87,175,349,699,1397,2794,5588,
	23,46,93,185,370,740,1475,2960,5920,
	25,49,98,196,392,784,1568,3136,6272,
	26,52,104,208,415,831,1661,3322,6645,
	28,55,110,220,440,880,1760,3520,7040,
	29,58,117,233,466,932,1865,3729,7459,
	31,62,124,247,494,988,1976,3951,7902
};


enum {
	DO = 0,
	DO_S,
	RE,
	RE_S,
	MI,
	FA,
	FA_S,
	SOL,
	SOL_S,
	LA,
	LA_S,
	TI,
	BR	//Break.
};

void playWholeNotes(void)
{
	int notes[7] = {DO,RE,MI,FA,SOL,LA,TI};
	for(int octave = 0; octave<9; octave++)
	{
		writeDebugStream("%d octave-------\n",octave);
		for(int n=0;n<7;n++)
		{
			writeDebugStream("%d\n",n);
			playTone(MUSIC_NOTE[notes[n]][octave],30);
			while(bSoundActive);
		}
	}
}

int Fly_Fly_Airplane[] = {MI,RE,DO,RE,MI,MI,MI,RE,RE,RE,MI,MI,MI,MI,RE,DO,RE,MI,MI,MI,RE,RE,MI,RE,DO};


/*
We need tempo for complete song.
*/
int JingleBell[] = {DO,LA,SOL,FA,DO,DO,LA,SOL,FA,RE,RE,TI,LA,SOL,MI,DO,DO,TI,SOL,LA,BR,BR,DO,LA,SOL,FA,DO,DO,LA,SOL,FA,RE,BR,BR,RE,TI,LA,SOL,BR,BR,DO,DO,DO,DO,BR,RE
	,DO,TI,SOL,FA,BR,BR,LA,LA,LA,BR,LA,LA,LA,BR,LA,DO,BR,FA,SOL,LA,BR,BR,TI,TI,TI,TI,BR,TI,LA,LA,LA,BR,LA,SOL,SOL,BR,FA,SOL,BR,DO,BR,BR,LA,LA,LA,BR,LA,LA,LA
	,BR,LA,DO,BR,FA,SOL,LA,BR,BR,TI,TI,TI,TI,BR,TI,LA,LA,LA,BR,DO,DO,BR,TI,SOL,FA};

task main()
{
	clearDebugStream();
	int n = sizeof(Fly_Fly_Airplane) / sizeof(int);
	for(int i =0;i<n;i++)
	{
		setSoundVolume(1);
		if(JingleBell[i] == BR)
		{
			playTone(0,30);
		}
		else{
			playTone(MUSIC_NOTE[Fly_Fly_Airplane[i]][4],30);
		}
		while(bSoundActive);
	}
}
