#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          actuator,      tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	int rotating_deg = 0;
	srand(nSysTime);
	int angle_min = 1500;
	int angle_max = angle_min+1000;


	while(true)
	{
		while(true)
		{
			if(getButtonPress(buttonLeft))
			{
				while(getButtonPress(buttonLeft))
				{
					setMotorSpeed(actuator, 20);
				}
				setMotorSpeed(actuator, 0);
			}

			if(getButtonPress(buttonRight))
			{
				while(getButtonPress(buttonRight))
				{
					setMotorSpeed(actuator, -20);
				}
				setMotorSpeed(actuator, 0);
			}
			if(getTouchValue(touchSensor) == 1)
			{
				while(getTouchValue(touchSensor) ==1)
				{
				}
				break;
			}
		}

		rotating_deg = rand()%(angle_max - angle_min) + angle_min;
		rotating_deg *= (rand()%2)?1:-1;
		moveMotorTarget(actuator, rotating_deg, sgn(rotating_deg)*30);
		waitUntilMotorStop(actuator);
	}

}
