#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
	This demonstration is about reproducing color, detected by color sensor, through the led on the EV3 brick.
	Only 3 colors , joint color of [what led can express] and [what color sensor can detect], are available.
	Black, Red and Green.
	If no color is detected, your led will flick frequently in orange color.
	Otherwise, flicking in red color.

	It was found out that the reliability is depending on the material, texture of the object you want to sense.
	As far as I know, objects like cloth, cotton were not sensible reliably.
*/
task main()
{

	while(1)
	{
		long color = getColorName(colorSensor);
		switch(color)
		{
			case colorNone:
			setLEDColor(ledOrangePulse);
			break;

			case colorBlack:
			setLEDColor(ledOff);
			break;

			case colorRed:
			setLEDColor(ledRed);
			break;

			case colorGreen:
			setLEDColor(ledGreen);
			break;

			default:
			setLEDColor(ledRedPulse);
			break;
		}
		wait1Msec(1000);
	}

}

