#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

/*
	?0 = No button (buttonNone)
	?1 = Up button (buttonUp)
	?2 = Enter button (buttonEnter)
	?3 = Down button (buttonDown)
	?4 = Right button (buttonRight)
	?5 = Left button (buttonLeft)
	?6 = Back button (buttonBack)
	?7 = Any button (buttonAny)
*/

	writeDebugStreamLine("getColorName");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorName(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	writeDebugStreamLine("getColorHue");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorHue(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	writeDebugStreamLine("getColorAmbient");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorAmbient(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	writeDebugStreamLine("getColorReflected");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorReflected(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	writeDebugStreamLine("getColorSaturation");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorSaturation(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	writeDebugStreamLine("getColorRGB");
	long R,G,B;
	while(!getButtonPress(2)){
		getColorRGB(colorSensor,R,G,B);
		writeDebugStreamLine("%6d %6d %6d",R,G,B );
		wait1Msec(50);
	}
	wait1Msec(500);

}
