#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	With your color sensor, sensing 6 different properties are available. But I guess only one property at once.
	In this demonstration, we will use all of them.
	And you can monitor the value through debugstream window. You can find it in Robot->Debugger Windows->Debug Stream.
	You can get to the next step by pressing [Enter Button] or [Button in the center].
*/


task main()
{
	/*
	Color Name
	If you want to see the list of sensible colors,
	go to the definition of TLegoColors.
	*/
	writeDebugStreamLine("getColorName");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorName(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	/*
	Color Hue.
	*/
	writeDebugStreamLine("getColorHue");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorHue(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	/*
	Ambient
	*/
	writeDebugStreamLine("getColorAmbient");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorAmbient(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	/*
	Reflected
	*/
	writeDebugStreamLine("getColorReflected");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorReflected(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	/*
	ColorSaturation
	*/
	writeDebugStreamLine("getColorSaturation");
	while(!getButtonPress(2)){
		writeDebugStreamLine("%6d", getColorSaturation(colorSensor));
		wait1Msec(50);
	}
	wait1Msec(500);

	/*
	ColorRGB
	*/
	writeDebugStreamLine("getColorRGB");
	long R,G,B;
	while(!getButtonPress(2)){
		getColorRGB(colorSensor,R,G,B);
		writeDebugStreamLine("%6d %6d %6d",R,G,B);
		wait1Msec(50);
	}
	wait1Msec(500);

}
