#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  float R = 56 * 0.5 * 0.001;
  float D = 0.6;

  //Forward 0.6m
  float degrees_for_forward = 0.6 / R * 180.0 / PI;
  setLEDColor(ledRedFlash);
  moveMotorTarget(leftMotor, degrees_for_forward, sgn(degrees_for_forward)*50);
  moveMotorTarget(rightMotor, degrees_for_forward, sgn(degrees_for_forward)*50);
  waitUntilMotorStop(leftMotor);
  waitUntilMotorStop(rightMotor);

  //Wait for 1 sec
  setLEDColor(ledOrangeFlash);
  wait1Msec(1000);

  //Backward 0.6m
  float degrees_for_backward = - 0.6 / R * 180.0 / PI;
  setLEDColor(ledRedFlash);
  moveMotorTarget(leftMotor, degrees_for_backward, sgn(degrees_for_backward)*50);
  moveMotorTarget(rightMotor, degrees_for_backward, sgn(degrees_for_backward)*50);
  waitUntilMotorStop(leftMotor);
  waitUntilMotorStop(rightMotor);

  //Wait for 1 sec
  setLEDColor(ledOrangeFlash);
  wait1Msec(1000);

  //Forward with speed of 40 for 2 sec.
  setLEDColor(ledRedFlash);
  setMotorSpeed(leftMotor, 60);
  setMotorSpeed(rightMotor, 60);
  wait1Msec(2000);
  setMotorSpeed(leftMotor,0);
  setMotorSpeed(rightMotor,0);

  //wait for 1 sec
  setLEDColor(ledOrangeFlash);
  wait1Msec(1000);

  //Set Motor Position to 0.
  setLEDColor(ledRedFlash);
  setMotorTarget(leftMotor, 0,60);
  setMotorTarget(rightMotor, 0,60);
  waitUntilMotorStop(leftMotor);
  waitUntilMotorStop(rightMotor);

  setLEDColor(ledOff);
}
